name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Fix index.html for File Explorer (Optional but helpful)
        run: |
          node -e "const fs=require('fs'); const p='dist/ms-sarker/browser/index.html'; if(fs.existsSync(p)){fs.writeFileSync(p, fs.readFileSync(p, 'utf8').replace(/type=\"module\"/g, ''))}"

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the default output path in angular.json
          path: dist/ms-sarker/browser/

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
